### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by demuxer** [ActivityWatch/aw-watcher-spotify#14]
When executing the poetry for the first time, this is the output:

```
$ poetry run aw-watcher-spotify
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/linuxbrew/.linuxbrew/opt/python@3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/demuxer/aw-watcher-spotify/aw_watcher_spotify/__init__.py", line 1, in <module>
    from .main import main
  File "/home/demuxer/aw-watcher-spotify/aw_watcher_spotify/main.py", line 11, in <module>
    from requests import ConnectionError
ModuleNotFoundError: No module named 'requests'
```

So, that's not clear to know what config.file must be filled in order to stat the watcher.

**Comment by ErikBjare** [comment]
Looks like you didn't run `poetry install`
