### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by flowingblaze** [ActivityWatch/aw-watcher-spotify#22]
Hello, I was trying to install the spotify watcher and I ran into an issue with installing it. After making sure I had pip installed I tried to run the py file using the "python -m main" command and I got this error: 

C:\Users\[name]\Downloads\aw-watcher-spotify-master\aw-watcher-spotify-master\aw_watcher_spotify>python -m main
Traceback (most recent call last):
  File "C:\Users\[name]\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\[name]\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\[name]\Downloads\aw-watcher-spotify-master\aw-watcher-spotify-master\aw_watcher_spotify\main.py", line 11, in <module>
    from requests import ConnectionError
ModuleNotFoundError: No module named 'requests'

I am aware that it is supposed to give an error so you can go and fill in the config file as stated in the readme, but there is no config file mentioned in this error, however I could be reading this wrong but I am pretty sure this isn't the error that I'm supposed to get.

**Comment by ErikBjare** [comment]
Looks like you didn't install dependencies as per the instructions. Closing this as it's not an issue with the project itself.
